services:
    migrations-apply:
        container_name: service-migrations-apply
        build:
          context: .
          dockerfile: PatteDoie/Dockerfile
          target: migrations-apply
        entrypoint: "dotnet ef database update"