services:
    migrations-apply:
        container_name: service-migrations-apply
        build:
            context: ../
            dockerfile: PatteDoie/DockerfileDatabase
        entrypoint: "dotnet ef database update"
        labels:
          com.microsoft.visualstudio.debuggee.program: "dotnet"
          com.microsoft.visualstudio.debuggee.arguments: ""

    migrations-create:
        container_name: service-migrations-create
        environment:
            - MIGRATION_NAME=${MIGRATION_NAME}
        build:
            context: ../
            dockerfile: PatteDoie/DockerfileDatabase
        entrypoint: "bash -c \"dotnet ef migrations add $${MIGRATION_NAME}\""
        labels:
          com.microsoft.visualstudio.debuggee.program: "dotnet"
          com.microsoft.visualstudio.debuggee.arguments: ""